# Generated by Django 3.1.2 on 2020-10-16 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_auto_20201016_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.major'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.student'),
        ),
    ]
