# Generated by Django 3.1.2 on 2020-10-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0004_auto_20201016_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
