# Generated by Django 3.1.2 on 2020-10-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0005_delete_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='college',
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='highSchoolGPA',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='maturaGrade',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.DeleteModel(
            name='College',
        ),
    ]
