# Generated by Django 3.1.2 on 2020-10-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0006_auto_20201026_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
